### ISSUE TITLE
Attach a file in Allure Report(C#) Dotnet core

### ISSUE THREAD

**Issue by santhosh-James** [allure-framework/allure-csharp#25]
Not able attach a file in Allurereport using Nunit and .netcore

here is the code i am using. 
AllureLifecycle.Instance.AddAttachment("Attachment Title", "application/txt", @"C:\Testing\AllureTest.txt");
it gives the follwoing exception 

Value cannot be null. Parameter name: key

StackTrace: 
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Allure.Commons.Storage.AllureStorage.Get[T](String uuid)
   at Allure.Commons.AllureLifecycle.AddAttachment(String name, String type, Byte[] content, String fileExtension)
   at Allure.Commons.AllureLifecycle.AddAttachment(String name, String type, String path)
   at 
)

- Allure version:      Nunit.Allure(1.0.5)
- Test framework:      Nunit(3.11.0)

Also, i used the code below. This also gives the same error

AllureLifecycle.AddAttachment("Attachment Title", "application/txt", @"C:\Testing\AllureTest.txt");

So how does an attachment can be added?

**Comment by nick-beers** [comment]
To try giving you some idea as to how this works. I ran into the same issue and used the [Integration Test](https://github.com/allure-framework/allure-csharp/blob/bcf18f1da3277d4bf47659f0093b928a08694cc4/Allure.Commons.Tests/AllureLifeCycleTest.cs) to make progress until I've become unfortunately stuck. You may need to generate a TestContainer instance and add the attachment to the test container instance. Thats the only way I was able to get it to work.

I'm stuck because I'm trying to use XUnit and the test containers I generate don't appear to attach correctly when running the Allure report to render results and screenshots. There isn't a reference to the TestContainers in the TestResults.xml file that XUnit generates, nor does there seem to be a method that will cause the Allure command line to pick up the contianer.json files that are generated with the test results.

Would the developers be able to provide an example of how to properly attach a file using .NET Core XUnit/NUnit or more specifically a screenshot/image to associate with a test?

**Comment by unickq** [comment]
@nick-beers 
I can't say anything about XUnit, but I've never faced with attachments issue with NUnit. Just ran 1.0.7 [Allure NUnit](https://github.com/unickq/allure-nunit) with netcore22 - looks fine.

@santhosh-James 
The code you use if fine - but it depends where you execute it. SetUp/TearDown/OneTimeSetup/etc
So paste full code, at least the code where Allure is using.

**Comment by unickq** [comment]
@santhosh-James 
Looks like I found what's wrong. You're trying to attach files in **OneTimeSetUp** or **OneTimeTearDown** methods. Unfortunately, it's not possible because **AllureNUnit** is built over [Action-Attributes](https://github.com/nunit/docs/wiki/Action-Attributes) and test can't get any info from global setup/teardown methods - https://github.com/nunit/nunit/issues/2103#issuecomment-291948488

So you can attach files in [**Test**]/[**SetUp**]/[**TearDown**] methods only and it's not related to dotnet core

**Comment by santhosh-James** [comment]
Nick- can you give a sample code?

**Comment by nick-beers** [comment]
So after some additional research my issue is entirely a problem related to xunit. The attachments actually do work,  but theres no concept of TestContext in the current released version of XUnit. Thus I can't write the proper wrappers to generate a valid Test Results output that allure can use.  I got it working using your recommendations for NUnit though, so thanks!
